apiVersion: v1
kind: Secret
metadata:
  name: seldon-rclone-env-secret
  namespace: mlflow
type: Opaque
stringData:
  RCLONE_CONFIG_S3_TYPE: "s3"
  RCLONE_CONFIG_S3_PROVIDER: "Minio"
  RCLONE_CONFIG_S3_ENV_AUTH: "true"
  RCLONE_CONFIG_S3_ACCESS_KEY_ID: "mlflow_minio_user"
  RCLONE_CONFIG_S3_SECRET_ACCESS_KEY: "mlflow_minio_password"
  RCLONE_CONFIG_S3_ENDPOINT: "http://mlflow-release-minio.mlflow.svc.cluster.local:9000"
  RCLONE_CONFIG_S3_REGION: "us-east-1"
  AWS_ENDPOINT_URL: "http://mlflow-release-minio.mlflow.svc.cluster.local:9000"
  AWS_ACCESS_KEY_ID: "mlflow_minio_user"
  AWS_SECRET_ACCESS_KEY: "mlflow_minio_password"
  S3_USE_HTTPS: "0"
  S3_VERIFY_SSL: "0"
